drop type if exists action_type, dragon_characteristic,cage_type,color,day_time,dragon_status,gender,season,transfer_type,terrain,worker_type,training_level,size cascade;
drop table if exists  action_type_influence,bag,cages,caring_and_train_actions,characteristic_levels,
children,classes,dragon_appearance,dragon_carers_trainers,dragon_characteristics,dragon_couples,dragon_diet,dragon_types,
dragons,evidence,find_types,food,habitat,messages,orders,people,places,search_member,search_outing,search_teams,search_types,seartch_history,
tamer_outing,tamer_outing_history,taming_stage,things,transfer_dragon_history,transfer_dragon_results,use_things,workers,terrains,dragon_abilities,classes_to_abilities cascade;
